/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import kontroler.Kontroler;


public class FGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FGlavna
     *
     * @param loggedUser
     */
    public FGlavna() {
        initComponents();
        setTitle("Aplikcaija:Ski škola, Dobrodošli nazad " + Kontroler.getLoggedUser().getIme());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmRadSaClanovima = new javax.swing.JMenu();
        jmiUnosNovogClana = new javax.swing.JMenuItem();
        jmiPretragaClanova = new javax.swing.JMenuItem();
        jmTrener = new javax.swing.JMenu();
        jmiPodaciOTreneru = new javax.swing.JMenuItem();
        jmOAplikaciji = new javax.swing.JMenu();
        jmiAutor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikcaija:Ski škola");

        jmRadSaClanovima.setText("Rad sa članovima");

        jmiUnosNovogClana.setText("Unos novog člana");
        jmiUnosNovogClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosNovogClanaActionPerformed(evt);
            }
        });
        jmRadSaClanovima.add(jmiUnosNovogClana);

        jmiPretragaClanova.setText("Pretraga članova");
        jmiPretragaClanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaClanovaActionPerformed(evt);
            }
        });
        jmRadSaClanovima.add(jmiPretragaClanova);

        jMenuBar1.add(jmRadSaClanovima);

        jmTrener.setText("Trener");

        jmiPodaciOTreneru.setText("Podaci o treneru");
        jmiPodaciOTreneru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPodaciOTreneruActionPerformed(evt);
            }
        });
        jmTrener.add(jmiPodaciOTreneru);

        jMenuBar1.add(jmTrener);

        jmOAplikaciji.setText("O aplikaciji");

        jmiAutor.setText("Autor");
        jmiAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAutorActionPerformed(evt);
            }
        });
        jmOAplikaciji.add(jmiAutor);

        jMenuBar1.add(jmOAplikaciji);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosNovogClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosNovogClanaActionPerformed
        FClan clan = new FClan(this, true, false);
        clan.setVisible(true);
    }//GEN-LAST:event_jmiUnosNovogClanaActionPerformed

    private void jmiPretragaClanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaClanovaActionPerformed
        FPretragaClanova pretragaClanova = new FPretragaClanova(this, true);
        pretragaClanova.setSize(1000, 400);
        pretragaClanova.setVisible(true);
    }//GEN-LAST:event_jmiPretragaClanovaActionPerformed

    private void jmiAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAutorActionPerformed
        FAutor fAutor = new FAutor(this, true);
        fAutor.setVisible(true);
    }//GEN-LAST:event_jmiAutorActionPerformed

    private void jmiPodaciOTreneruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPodaciOTreneruActionPerformed
        FTrener fTrener = new FTrener(this, true);
        fTrener.setVisible(true);
    }//GEN-LAST:event_jmiPodaciOTreneruActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmOAplikaciji;
    private javax.swing.JMenu jmRadSaClanovima;
    private javax.swing.JMenu jmTrener;
    private javax.swing.JMenuItem jmiAutor;
    private javax.swing.JMenuItem jmiPodaciOTreneru;
    private javax.swing.JMenuItem jmiPretragaClanova;
    private javax.swing.JMenuItem jmiUnosNovogClana;
    // End of variables declaration//GEN-END:variables
}
