/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Clan;
import domen.Trener;
import domen.Trening;
import domen.VrstaTreninga;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ModelTabeleTrening;
import komunikacija.KomunikacijaSaServerom;
import kontroler.Kontroler;
import pomoc.Operacija;
import pomoc.StatusOdgovora;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;


public class FTrening extends javax.swing.JDialog {

    /**
     * Creates new form FTrening
     */
    public FTrening(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
        popuniComboTrener();
        popuniComboVrstaTreninga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDuzinaTrajanja = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldICilj = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTreninzi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBoxVrstaTreninga = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jComboBoxTrener = new javax.swing.JComboBox();
        jComboBoxIgrac = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSadrzaj = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos novog treninga");

        jLabel1.setText("Trener:");

        jLabel2.setText("Igrač:");

        jLabel3.setText("Datum (dd.MM.yyyy):");

        jLabel4.setText("Vrsta treninga:");

        jLabel5.setText("Dužina trajanja (u minutima):");

        jLabel6.setText("Cilj:");

        jLabel7.setText("Sadržaj:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Treninzi"));

        jTableTreninzi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTreninzi);

        jButton1.setText("Sačuvaj treninge");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1))
        );

        jButton2.setText("Dodaj ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxTrener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTrenerActionPerformed(evt);
            }
        });

        jComboBoxIgrac.setEnabled(false);

        jButton3.setText("Obriši");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextAreaSadrzaj.setColumns(20);
        jTextAreaSadrzaj.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSadrzaj);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addComponent(jTextFieldDuzinaTrajanja)
                            .addComponent(jTextFieldICilj)
                            .addComponent(jTextFieldDatum)
                            .addComponent(jComboBoxVrstaTreninga, 0, 278, Short.MAX_VALUE)
                            .addComponent(jComboBoxTrener, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxIgrac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxIgrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxVrstaTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDuzinaTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldICilj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ModelTabeleTrening mtt = (ModelTabeleTrening) jTableTreninzi.getModel();
        List<Trening> treninzi = mtt.vratiTreninge();
        try {
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setAkcija(Operacija.SACUVAJ_LISTU_ODO);
            kz.setParametar(treninzi);
            KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
            ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();
            if (so.getStatus() == StatusOdgovora.OK) {
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio treninge", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
                resetujFormu();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti treninge", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Trener t = (Trener) jComboBoxTrener.getSelectedItem();
        Clan c = (Clan) jComboBoxIgrac.getSelectedItem();
        String dat = jTextFieldDatum.getText().trim();
        VrstaTreninga vt = (VrstaTreninga) jComboBoxVrstaTreninga.getSelectedItem();
        String duzTrajanja = jTextFieldDuzinaTrajanja.getText().trim();
        String cilj = jTextFieldICilj.getText().trim();
        String sadrzaj = jTextAreaSadrzaj.getText().trim();
        if (dat.isEmpty() || duzTrajanja.isEmpty() || cilj.isEmpty() || sadrzaj.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date datum = null;
        try {
            datum = sdf.parse(dat);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Datum morate uneti u formatu dd.MM.yyyy", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int duzinaTrajanja = 0;
        try {
            duzinaTrajanja = Integer.parseInt(duzTrajanja);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "U polje dužina trajanja morate uneti broj", "Upozorenje", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Trening trening = new Trening();
        trening.setTrener(t);
        trening.setClan(c);
        trening.setDatum(datum);
        trening.setDuzinaTrajanja(duzinaTrajanja);
        trening.setCilj(cilj);
        trening.setSadrzaj(sadrzaj);
        trening.setVrstaTreninga(vt);
        ModelTabeleTrening mtt = (ModelTabeleTrening) jTableTreninzi.getModel();
        mtt.dodaj(trening);
        jTextFieldDatum.setText("");
        jComboBoxVrstaTreninga.setSelectedIndex(0);
        jTextFieldDuzinaTrajanja.setText("");
        jTextFieldICilj.setText("");
        jTextAreaSadrzaj.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int red = jTableTreninzi.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati red u tabeli", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ModelTabeleTrening mtt = (ModelTabeleTrening) jTableTreninzi.getModel();
        mtt.obrisi(red);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxTrenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTrenerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTrenerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBoxIgrac;
    private javax.swing.JComboBox jComboBoxTrener;
    private javax.swing.JComboBox jComboBoxVrstaTreninga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTreninzi;
    private javax.swing.JTextArea jTextAreaSadrzaj;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldDuzinaTrajanja;
    private javax.swing.JTextField jTextFieldICilj;
    // End of variables declaration//GEN-END:variables

    void postaviParametre(Clan c) {
        jComboBoxIgrac.addItem(c);
        jComboBoxTrener.setSelectedItem(Kontroler.getLoggedUser());
    }

    private void srediFormu() {
        ModelTabeleTrening mtt = new ModelTabeleTrening();
        jTableTreninzi.setModel(mtt);
        srediKoloneTabele();
    }

    private void popuniComboVrstaTreninga() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setAkcija(Operacija.VRATI_SVE_ZA_ODO);
        kz.setParametar(new VrstaTreninga());

        try {
            KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
            ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();
            jComboBoxVrstaTreninga.removeAllItems();
            if (so.getStatus() == StatusOdgovora.OK) {
                List<VrstaTreninga> lista = (List<VrstaTreninga>) so.getOdgovor();
                for (VrstaTreninga vrstaTreninga : lista) {
                    jComboBoxVrstaTreninga.addItem(vrstaTreninga);
                }
            }

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FClan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void popuniComboTrener() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setAkcija(Operacija.VRATI_SVE_ZA_ODO);
        kz.setParametar(new Trener());
        try {
            KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
            ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();
            jComboBoxTrener.removeAllItems();

            if (so.getStatus() == StatusOdgovora.OK) {

                List<Trener> lista = (List<Trener>) so.getOdgovor();
                for (Trener trener : lista) {
                    jComboBoxTrener.addItem(trener);
                }
            }

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FClan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void resetujFormu() {
        srediFormu();
        jComboBoxTrener.setSelectedIndex(0);
        jTextFieldDatum.setText("");
        jComboBoxVrstaTreninga.setSelectedIndex(0);
        jTextFieldDuzinaTrajanja.setText("");
        jTextFieldICilj.setText("");
        jTextAreaSadrzaj.setText("");
    }

    private void srediKoloneTabele() {
        jTableTreninzi.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTableTreninzi.getColumnModel().getColumn(1).setPreferredWidth(60);
        jTableTreninzi.getColumnModel().getColumn(2).setPreferredWidth(95);
        jTableTreninzi.getColumnModel().getColumn(3).setPreferredWidth(95);
        jTableTreninzi.getColumnModel().getColumn(4).setPreferredWidth(125);
        jTableTreninzi.getColumnModel().getColumn(5).setPreferredWidth(175);
    }

}
